<a href="https://colab.research.google.com/github/Aaryan24/bcs-fap-1/blob/main/Week1_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part 1**

### **Load the Dataset**

In [52]:
# importing pandas module as pd (shortform) and then using read_csv function to read the csv from its file path
import pandas as pd

data = pd.read_csv('/content/sample_data/california_housing_train.csv')
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

### **Data Summary**

In [53]:
# using describe function to find all stats for each column with numerical data
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [90]:
# using loop i check for values and add it in the list, if its already present then it does nothing and moves ahead
list = []
for i in range (0,17000):
  n = data['total_bedrooms'][i]
  if n in list:
    pass
  else:
    list.append(n)

#print(list)
print("Distinct values of total_bedrooms: ",len(list))

Distinct values of total_bedrooms:  1848



### **Data Transformation**

In [55]:
# using loop i calculate the reqd. value and add it to a list and then add a column to 'data' assigning it to the list
list2 = []
for i in range(0,17000):
  final = (data['total_bedrooms'][i]) / (data['total_rooms'][i])
  list2.append(final)

data['total_bedrooms_per_total_rooms'] = list2
data.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   

   population  households  median_income  median_house_value  \
0      1015.0       472.0         1.4936             66900.0   
1      1129.0       463.0         1.8200             80100.0   

   total_bedrooms_per_total_rooms  
0                        0.228617  
1                        0.248497

In [56]:
# using describe to get a dataframe called summary which has all info and then extracting particular reqd. info from it
summary = data.describe()
print("Mean: ", summary['total_bedrooms_per_total_rooms']['mean'])
print("Standard Deviation: ", summary['total_bedrooms_per_total_rooms']['std'])

Mean:  0.21275998821034803
Standard Deviation:  0.057823008903161756


### **Data Filtering**


In [57]:
# filtering those rows where median income is more than 5
dataset_1 = data[data['median_income']>5]
dataset_1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [58]:
# filtering based on conditions -- usage of & is necessary, 'and' won't work as these are not boolean values
dataset_2 = data[(data['total_rooms']>10000) & (data['median_house_value']<150000)]
dataset_2

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

### **Export Modified Data**

In [59]:
data.to_csv('modified_data.csv')

# **Part - 2**

### **Array Creation and Indexing**



In [64]:
#1 Here I make a list via loop to contain all 20 integers and then make it a np array
import numpy as np
l = []
for i in range(1,21):
  l.append(i)
arr1 = np.array(l)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
#2 Here I use slicing with start, stop and a step of 2 to take alternative numbers  i.e. even nos.
arr2 = arr1[1:20:2]
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [66]:
#3 First I create an array of 20 elements as specified and then reshape it to 5 row, 4 column
arr3 = np.random.randint(10,101,20)
arr3_reshaped = arr3.reshape(5,4)
arr3_reshaped

array([[15, 85, 99, 57],
       [13, 91, 58, 84],
       [81, 92, 97, 35],
       [68, 40, 58, 38],
       [71, 38, 33, 68]])

In [67]:
#4 Used slicing to extract subarray
arr3_modified = arr3_reshaped[0:4, 0:2]
arr3_modified

array([[15, 85],
       [13, 91],
       [81, 92],
       [68, 40]])

### **Array Manipulation**

In [68]:
#1
arr1_reshaped = arr1.reshape(4,5)
arr1_reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [69]:
#2
arr1_reshaped_converted = arr1_reshaped.flatten()
arr1_reshaped_converted

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [70]:
#3 Used the builtin function to perform matri multiplcation after generating a random matrix 5x1
arr4 = np.random.randint(10,31, 5)
arr4 = arr4.reshape(5,1)

#matrix multiplication
mul_matrix = np.matmul(arr1_reshaped, arr4)
mul_matrix

array([[ 258],
       [ 663],
       [1068],
       [1473]])

### **Boolean and Fancy Indexing**

In [71]:
#1
arr = np.random.randint(0,101,10)
arr

array([ 14,  56,  70,  96,   1,  55, 100,   9,  31,  92])

In [72]:
#2 Created a mask (arr>50) and applied it on arr to extract elements greater than 50
arr_bool = arr[arr>50]
arr_bool

array([ 56,  70,  96,  55, 100,  92])

In [73]:
#3 Used fancy indexing to extract elements at index 0 and 3
fancy_index = [0,3]
arr_fancy = arr[fancy_index]
arr_fancy

array([14, 96])

### **Statistical Operations**

In [74]:
arr3_reshaped

array([[15, 85, 99, 57],
       [13, 91, 58, 84],
       [81, 92, 97, 35],
       [68, 40, 58, 38],
       [71, 38, 33, 68]])

In [75]:
# I create lists to store data for each column, then just create a loop to select each column calculate the stats
# and just add it to the respective list. A mask is created for each column and then applied on each column to
# obtain the array of reqd. values and convert it to list and add the values in this list to a master list - 'empty_list'
# finally i print all these lists and the empty_list as an array
mean_list = []
max_list = []
sum_list = []
empty_list = []

for i in range(0,4):
  mean = arr3_reshaped[:,i].mean()
  max = arr3_reshaped[:,i].max()
  sum = arr3_reshaped[:,i].sum()

  mask = arr3_reshaped[:,i]>mean

  l = (arr3_reshaped[:,i][mask]).tolist()
  for j in range(0, len(l)):
    empty_list.append(l[j])

  mean_list.append(mean)
  max_list.append(max)
  sum_list.append(sum)

print(mean_list, max_list, sum_list)
print(np.array(empty_list))

[49.6, 69.2, 69.0, 56.4] [81, 92, 99, 84] [248, 346, 345, 282]
[81 68 71 85 91 92 99 97 57 84 68]


# **Part 3**

### **Loops and Conditional Statements**

In [60]:
#1 using infinite running loop to get the fibonacci nos (by adding the last 2 elements of the list)
# with a break condition that if the number to be appended > 100 then break the loop
list = [0,1]

while True:
  n = len(list)
  if list[n-1]+list[n-2] > 100:
    break
  list.append(list[n-1]+list[n-2])


print(list)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [61]:
#2
for i in range(1,51):
  if i%3==0 and i%5==0:
    print("FizzBuzz", i)
  elif i%5==0:
    print("Buzz", i)
  elif i%3==0:
    print("Fizz", i)

Fizz 3
Buzz 5
Fizz 6
Fizz 9
Buzz 10
Fizz 12
FizzBuzz 15
Fizz 18
Buzz 20
Fizz 21
Fizz 24
Buzz 25
Fizz 27
FizzBuzz 30
Fizz 33
Buzz 35
Fizz 36
Fizz 39
Buzz 40
Fizz 42
FizzBuzz 45
Fizz 48
Buzz 50


### **Variable-Length Arguments**

In [62]:
#1 and 2
l = []
n = int(input("How many numbers?: "))
for i in range(0,n):
  x = int(input("Enter number: "))
  l.append(x)

sum = 0
for i in l:
  sum  = sum + i


l.sort()
if n%2 == 0:
  print("Median: ", (l[(n-1)//2]+l[((n-1)//2)+1])/2)
else:
  print("Median: ", l[(n-1)//2])

print("Average of numbers: ", sum/n)

How many numbers?: 4
Enter number: 1
Enter number: 2
Enter number: 3
Enter number: 4
Median:  2.5
Average of numbers:  2.5


### **Error Handling**


In [63]:
#1
n1 = float(input("Enter number 1: "))
n2 = float(input("Enter number 2: "))

try:
  division = n1/n2
except Exception as e:
  print("Error: ",e)
else:
  division = n1/n2
  print("Division: ", division)

Enter number 1: 4
Enter number 2: 0
Error:  float division by zero


# **Bonus Challenge**

In [78]:
#1 Generating a random 3d array
ar = np.random.randint(0,20,8)
ar_3d = ar.reshape(2,2,2)
ar_3d

array([[[ 8, 12],
        [18,  9]],

       [[12, 12],
        [14,  5]]])

In [83]:
#2 Swapping axes in 3d array (row and column swapped below, depth unchanged)
ar_3d.swapaxes(1,2)

array([[[ 8, 18],
        [12,  9]],

       [[12, 14],
        [12,  5]]])

In [84]:
#3 Finding sum of elements of array along a particular axis
np.sum(ar_3d, axis = 1)

array([[26, 21],
       [26, 17]])

In [89]:
#4 Adding a vector to 2d array
a = np.random.randint(0,20,(2,2))
w = [1,1]
sup = w + a
print(a)
print(sup)


[[19 13]
 [11 16]]
[[20 14]
 [12 17]]
